import MovixImage from "../assets/Movix.png";
import WeatherAppImage from "../assets/Weather.png";
import ChatAppImage from "../assets/ChatApp.png";
import DigitalClockImage from "../assets/DigitalClock.png";
import AdminDashboardImage from "../assets/AdminDashboard.png";
import BestJokesImage from "../assets/BestJokes.png";
import FakeShopImage from "../assets/FakeShop.png";
import GoogleKeepCloneImage from "../assets/GoogleKeepClone.png";
import StopWatchImage from "../assets/StopWatch.png";
import TicTacToeImage from "../assets/TicTacToe.png";
import TypingTestWeb from "../assets/TypingTestWeb.png";

export const projectsData = [
  {
    id: 1,
    name: "Movix",
    urlName: "Movix",
    description: "Get All Movies Information",
    technology: ["React", "Js", "Vite", "Redux"],
    gitLink: "https://github.com/Hrithik08-varshney/MOVIX",
    desc: "Movix is your ultimate movie companion, developed in React to deliver a seamless and engaging experience for film enthusiasts. With an intuitive interface, users can easily browse and search a vast library of movies, accessing detailed information such as synopses, cast and crew details, release dates, ratings, and genres. The app offers personalized recommendations tailored to your viewing preferences, along with user reviews and ratings to help you make informed choices. You can create and manage a watchlist to keep track of films you want to see, all while enjoying a responsive design that works beautifully across devices. Stay updated on the latest releases and discover hidden gems with Movix, making your movie-watching experience truly unforgettable!",
    deployLink: "https://neon-scone-84b4d4.netlify.app",
    image: MovixImage,
    fullDesc:"Built with React and Redux, this app offers a seamless experience for movie lovers. Explore detailed movie reviews, cast information, and trailers, all powered by API integration. Enjoy a responsive design, efficient state management, and real-time updates, making it your ultimate resource for discovering and discussing films!"
  },
  {
    id: 2,
    name: "React Weather App",
    urlName: "React-Weather-App",
    description: "Check the weather of your city",
    technology: ["React", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/React-Weather-App",
    deployLink: "https://thunderous-strudel-dccec7.netlify.app",
    image: WeatherAppImage,
    fullDesc:"Built with React and powered by API integration, this weather app provides real-time weather updates for any location. Users can effortlessly search for cities and view detailed forecasts, including temperature, humidity, and conditions. With a sleek and intuitive interface, stay informed about the weather wherever you go! Perfect for planning your day or your next adventure.",
    desc: "WeatherApp is a dynamic and user-friendly application built with React that brings the latest weather updates right to your fingertips. By integrating with the OpenWeather API, the app provides real-time weather data for locations around the globe. With a clean and intuitive interface, users can easily search for cities to access current conditions, forecasts, humidity levels, wind speeds, and more.",
  },
  {
    id: 3,
    name: "Aora",
    urlName: "Aora",
    description: "Tiktok similar Mobile App",
    technology: ["ReactNative", "Js", "Appwrite", "Expo", "Tailwind"],
    gitLink: "https://github.com/Hrithik08-varshney/React-Native-Learn-App",
    fullDesc:"Built with React Native and Expo, this mobile app offers an engaging platform for sharing short-form videos. Users can create, edit, and share their content while exploring a wide array of trending videos. Although the follow feature isn't implemented yet, the app provides a vibrant community experience through likes and comments, ensuring users can interact and connect with engaging content. With a sleek interface and smooth performance, this app is perfect for expressing creativity and enjoying entertaining videos!",
    desc: "Aora is a vibrant mobile application developed using React Native and powered by Expo, designed to create a dynamic and engaging social video-sharing experience similar to TikTok. With Aora, users can effortlessly create, edit, and share short videos, showcasing their creativity and connecting with a global community. To ensure seamless performance and user management, Aora’s backend is powered by Appwrite, providing robust features for authentication, database management, and real-time interactions.",
  },
  {
    id: 4,
    name: "Chat App",
    urlName: "Chat-App",
    description: "Built a group chat here",
    technology: ["NodeJs", "HTML", "CSS", "Js", "Socket"],
    gitLink: "https://github.com/Hrithik08-varshney/Chat-App",
    image: ChatAppImage,
    fullDesc:"Developed using Node.js, HTML, CSS, JavaScript, and Socket.io, this chat app enables real-time messaging between users. The intuitive interface allows participants to join chat rooms, send messages, and receive updates instantly. With responsive design and seamless socket communication, users can engage in lively conversations and connect with friends effortlessly. Ideal for learning about web sockets and real-time applications, this app showcases the power of modern web technologies in creating interactive experiences!",
    desc: "ChatApp is a sleek and responsive chat application designed for real-time communication, with a front end crafted using HTML, CSS, and JavaScript. The user-friendly interface allows users to easily send and receive messages, making it perfect for both casual conversations and group chats. On the back end, ChatApp leverages Node.js along with Socket.io to enable seamless real-time messaging. This powerful combination ensures instant message delivery and updates, keeping users connected without any lag. The app features user authentication, allowing users to create accounts and manage their profiles while enjoying a secure chatting environment.",
  },
  {
    id: 5,
    name: "FakeShop",
    urlName: "FakeShop",
    description: "Shopping App Clone",
    technology: ["React", "Js", "Vite", "Redux"],
    gitLink: "https://github.com/Hrithik08-varshney/fakeshop",
    deployLink: "https://poetic-faloodeh-2e7105.netlify.app",
    image: FakeShopImage,
    desc: "Shopping Clone is a feature-rich e-commerce application developed with React and powered by Redux for state management, designed to provide a seamless online shopping experience. This app mimics popular shopping platforms, allowing users to browse a wide array of products, add items to their cart, and make secure purchases with ease.",
  },
  {
    id: 6,
    name: "Inshort-Clone",
    urlName: "Inshort-Clone",
    description: "Read your daily news here",
    technology: ["React", "Js", "Redux"],
    gitLink: "https://github.com/Hrithik08-varshney/Inshort-Clone",
    desc: "Short App Clone is a sleek application developed with React that showcases the power of API integration and infinite scrolling. This app allows users to seamlessly browse through a vast collection of content without interruptions, providing an engaging user experience. With smooth navigation and a clean interface, users can effortlessly explore items, while the infinite scrolling feature ensures that new content loads automatically as they reach the bottom of the page. Perfect for discovering endless information, Short App Clone delivers a modern and efficient browsing experience!",
  },
  {
    id: 7,
    name: "ToDO List",
    urlName: "ToDO-List",
    description: "Add your daily task here",
    technology: ["React", "Firebase"],
    gitLink: "https://github.com/Hrithik08-varshney/Todo-List",
    deployLink: "https://gorgeous-faun-46b6fc.netlify.app",
    desc: "The ToDo List App is a simple yet powerful productivity tool developed using React, with a robust backend powered by Firebase. This app allows users to easily create, manage, and track their tasks in an intuitive interface. With real-time synchronization provided by Firebase, users can access their to-do lists from any device, ensuring that updates are instantly reflected across all platforms. The app features functionalities like adding, editing, and deleting tasks, as well as marking items as complete. Users can also categorize tasks and set deadlines to stay organized.",
  },
  {
    id: 8,
    name: "React Admin Dashboard",
    urlName: "React-Admin-Dashboard",
    description: "Admin portal for your business",
    technology: ["React", "SCSS"],
    gitLink: "https://github.com/Hrithik08-varshney/React-Admin-Dashboard",
    deployLink: "https://incandescent-speculoos-77bd4d.netlify.app",
    image: AdminDashboardImage,
    desc: "The Admin Dashboard is a powerful and customizable application developed using React and styled with SCSS, designed to provide an intuitive interface for managing various administrative tasks. With a modern and responsive design, this dashboard offers a seamless user experience across devices. Featuring a variety of pre-built components such as charts, tables, and forms, the dashboard allows administrators to easily monitor key metrics, manage users, and access detailed analytics. The use of SCSS ensures that the design is both flexible and maintainable, allowing for quick adjustments and enhancements.",
  },
  {
    id: 9,
    name: "Typing Test Website",
    urlName: "Typing-Test-Website",
    description: "Test your typing speed",
    technology: ["HTML", "CSS", "Js"],
    deployLink: "https://hrithik08-varshney.github.io/Typing-Test-Website/",
    gitLink: "https://github.com/Hrithik08-varshney/Typing-Test-Website",
    image: TypingTestWeb,
  },
  {
    id: 10,
    name: "Tic-Tac-Toe",
    urlName: "Tic-Tac-Toe",
    description: "Pass your time here with zero and kata",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Tic-Tac-Toe",
    deployLink: "https://hrithik08-varshney.github.io/Tic-Tac-Toe/",
    image: TicTacToeImage,
    desc: "The Tic Tac Toe game is a classic, interactive web application built with HTML, CSS, and JavaScript. This simple yet engaging game allows players to enjoy a fun challenge against a friend or the computer. With a clean and responsive design, the game features a 3x3 grid where players can take turns marking their spaces with X or O. The intuitive interface makes it easy to click on cells to make a move, and the game logic ensures that winning combinations are detected instantly.",
  },
  {
    id: 11,
    name: "Google Keep Clone",
    urlName: "Google-Keep-Clone",
    description: "Add your notes here",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Google-Keep-Clone",
    deployLink: "https://hrithik08-varshney.github.io/Google-Keep-Clone",
    image: GoogleKeepCloneImage,
    desc: "The Google Keep Clone is a web application designed to mimic the functionality of Google Keep, built using HTML, CSS, and JavaScript. This intuitive note-taking app allows users to create, edit, and organize notes in a visually appealing and user-friendly interface. Leveraging JavaScript for interactive elements, users can drag and drop notes to reorder them, delete unwanted notes, and search through their collection quickly. The Google Keep Clone provides a seamless experience for those looking to capture ideas, manage tasks, and stay organized—all in one convenient application!",
  },
  {
    id: 12,
    name: "Digital Clock",
    urlName: "Digital-Clock",
    description: "Check your time here",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Digital-Clock",
    deployLink: "https://hrithik08-varshney.github.io/Digital-Clock",
    image: DigitalClockImage,
    desc: "The Digital Clock is a simple yet elegant web application built with HTML, CSS, and JavaScript that displays the current time in a user-friendly format. This project features a clean and modern design, making it a stylish addition to any webpage. Using HTML for structure, CSS for styling, and JavaScript for functionality, the clock updates in real time, showcasing hours, minutes, and seconds. The design is fully responsive, ensuring that it looks great on both desktop and mobile devices.",
  },
  {
    id: 13,
    name: "Joke Website",
    urlName: "Joke-Website",
    description: "Pass your time with amazing jokes",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Joke-Website",
    deployLink: "https://hrithik08-varshney.github.io/Joke-Website",
    image: BestJokesImage,
    desc: "The Joke Website is a fun and interactive web application built with HTML, CSS, and JavaScript, featuring API integration to deliver a continuous stream of jokes. Designed for users looking to lighten their day, this site offers a simple and engaging interface that allows visitors to fetch and display jokes at the click of a button. Using HTML for the structure, CSS for a playful design, and JavaScript to handle API requests, the app connects to a joke API to retrieve random jokes. Users can easily navigate the site, with a button to generate new jokes and a section to display the latest laugh.",
  },
  {
    id: 14,
    name: "Stopwatch",
    urlName: "Stopwatch",
    description: "Use the stopwatch here",
    technology: ["HTML", "CSS", "Js", "SVG"],
    gitLink: "https://github.com/Hrithik08-varshney/StopWatch",
    deployLink: "https://hrithik08-varshney.github.io/StopWatch/",
    image: StopWatchImage,
    desc: "The Stopwatch is a sleek and functional web application built with HTML, CSS, JavaScript, and SVG graphics. This project provides users with a simple interface to track time easily, making it perfect for timing workouts, cooking, or any activity where precise timing is essential. Using HTML for structure, the stopwatch features clear, legible displays for minutes, seconds, and milliseconds. CSS styles the application with a modern and clean design, while SVG graphics enhance the visual appeal with smooth, scalable icons and buttons.",
  },
  {
    id: 15,
    name: "Review Carousel",
    urlName: "Review-Carousel",
    description: "Get latest reviews here",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Review-Carousel",
    desc: "The Review Carousel is an interactive web component designed to showcase customer testimonials and reviews in a visually appealing format. Built using HTML, CSS, and JavaScript, this carousel allows users to effortlessly browse through multiple reviews with a smooth sliding effect. Using HTML for structure, each review is displayed with the reviewer’s name, photo, and a short testimonial, creating a personal touch. CSS styles the carousel with a modern design, including animations and transitions that enhance the user experience.",
  },
  {
    id: 16,
    name: "Websites",
    urlName: "Websites",
    description: "Get Different types of website here",
    technology: ["HTML", "CSS", "Js"],
    gitLink: "https://github.com/Hrithik08-varshney/Different-Websites",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Github",
    link: "https://github.com/Hrithik08-varshney",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/hrithik-varshney-687206192/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "Leetcode",
    link: "https://leetcode.com/u/varshneyhrithik/",
    icon: "code",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/Hrithik-Varshney-Resume.pdf",
    icon: "resume",
    newTab: true,
  },
];
